apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-app
  namespace: status
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: status-app
  template:
    metadata:
      labels:
        app: status-app
    spec:
      imagePullSecrets:
      - name: ecr-pull-secret
      containers:
      - name: status-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: APP_VERSION
          value: "{{ .Values.image.tag }}"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi