apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-app
  namespace: status
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: status-app
  template:
    metadata:
      labels:
        app: status-app
    spec:
      containers:
      - name: status-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
