apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: status-app
  namespace: status
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: status-app-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: status-app
            port:
              number: {{ .Values.service.port }}
