apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wiki
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      volumes:
      - name: rds-ca
        configMap:
          name: rds-ca-cert
      containers:
      - name: wikijs
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: wikijs-db-secret
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /certs/ca.pem
        volumeMounts:
        - name: rds-ca
          mountPath: /certs
        resources:
          {{- toYaml .Values.resources | nindent 10 }}